CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
	codigo VARCHAR(10) UNIQUE NOT NULL,
    primer_nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    nombre_usuario VARCHAR(100) NOT NULL,
    correo_electronico VARCHAR(50) UNIQUE NOT NULL,
    contrasena VARCHAR(300) NOT NULL,
    id_pais INT NULL,
    id_ciudad INT NULL,
    numero_preguntas INT NULL,
    numero_respuestas INT NULL,
    id_rol INT NOT NULL,
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    eliminado BOOLEAN,
	CONSTRAINT fk_id_rol FOREIGN KEY (id_rol) REFERENCES rol(id),
	CONSTRAINT fk_id_pais FOREIGN KEY (id_pais) REFERENCES paises(id) ON DELETE SET NULL,
	CONSTRAINT fk_id_ciudad FOREIGN KEY (id_ciudad) REFERENCES ciudades(id) ON DELETE SET NULL
);